### ISSUE TITLE
2.1.0 breaks

### ISSUE THREAD

**Issue by testsys-bbordelon** [soundaranbu/Razor.Templating.Core#78] opened 2024-11-20 19:07 UTC
Not sure what's going on, but when I upgraded to 2.1.0, I get 404s.  2.0.0 works fine.  I don't have a lot of info, but there's definitely something different about how 2.1.0 works vs 2.0.0, and I didn't see any breaking changes listed anywhere

**Comment by asos-soundaranbalagan** [comment] 2024-11-20 19:18
Hey @testsys-bbordelon, thanks for reporting this. Could you please share some more information to reproduce this please? 
.NET version:
Which method of this library are you using?
Your Views setup:

**Comment by shanto-ael** [comment] 2024-12-19 11:33
@asos-soundaranbalagan I am facing some problem while publishing in IIS server production like 401 unauthorized. Is there anything to do? After publish, i didn't have views folder, i put that with cshtml file but still not working. Getting 401 for only this Api. It works fine on local.
```
 [HttpGet("GeneratePdf/{id}")]
    public async Task<IActionResult> GeneratePdf(Guid id){
        var userRecords = await _userSignService.GetByIdAsync(id);
        var userInfo = await _userService.GetByIdAsync(userRecords.UserId);
        var viewbag = new Dictionary<string, object>
        {
            ["FirstName"] = userInfo.FirstName,
            ["LastName"] = userInfo.LastName
        };
        string html = await _razorTemplateEngine.RenderAsync("~/Views/UserSignPdf.cshtml", userRecords, viewbag);
        var rs = new LocalReporting()
                        .KillRunningJsReportProcesses()
                        .UseBinary(RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? JsReportBinary.GetBinary() : jsreport.Binary.Linux.JsReportBinary.GetBinary())
                        .Configure(cfg => cfg.DoTrustUserCode().FileSystemStore().BaseUrlAsWorkingDirectory())
                        .AsUtility()
                        .Create();

        var generatedPdf = await rs.RenderAsync(new RenderRequest
        {
            Template = new Template
            {
                Recipe = Recipe.ChromePdf,
                Engine = Engine.None,
                Content = html,
                Chrome = new Chrome
                {
                    MarginTop = "10",
                    MarginBottom = "10",
                    MarginLeft = "50",
                    MarginRight = "50"
                }
            }
        });

        return File(generatedPdf.Content, generatedPdf.Meta.ContentType, $"User {userRecords.UserId}.pdf");
    }
```

**Comment by soundaranbu** [comment] 2024-12-19 11:43
Hey @shanto-ael, the views are compiled to the dll. So you'll no longer see the view files in the output in .NET 6+. 401 seems like an authentication issue rather than the issue with the template. I would suggest you to remove the authentication part and then try again in IIS and see how things are. Only if the library complains about view not being found, then we can look more into the library itself or how you've configured things for the rendering views. Does that makes sense?

**Comment by soundaranbu** [comment] 2024-12-23 09:58
Closing this as it looks like a duplicate of https://github.com/soundaranbu/Razor.Templating.Core/issues/80

**Closed by soundaranbu** 2024-12-23 09:58 UTC
Labels: needs-more-info
