### ISSUE TITLE
Can we have an overload of RenderAsync that takes a Stream?

### ISSUE THREAD

**Issue by omatrot** [soundaranbu/Razor.Templating.Core#69] opened 2024-03-14 14:19 UTC
Hello,
I'd like to use your library, but my cshtml files are embedded as resources in my assembly.
The previous code, that is using .NET 4.7.1, is extracting them as strings and calls `Engine.Razor.RunCompile`.
The way I see it, we could have a version of `RazorTemplateEngine.RenderAsync` that takes a Stream?
I have the read the documentation, and I may be wrong, bu I can't find a way to do it.

My project file that contains the views and the rendering code is like this:

```
<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Template\Sept-lieues\AnalyticsWeeklyReport.cshtml" />
    <EmbeddedResource Include="Template\Sept-lieues\AnalyticsMonthlyReport.cshtml" />
    <EmbeddedResource Include="Template\PSRH\AnalyticsMonthlyReport.cshtml" />
  </ItemGroup>
   <ItemGroup>
    <PackageReference Include="Razor.Templating.Core" Version="1.9.0" />
 </ItemGroup>
</Project>
```

And the exception:

```
System.InvalidOperationException: Unable to find view 'PSRH/AnalyticsMonthlyReport.cshtml'. The following locations were searched:
/PSRH/AnalyticsMonthlyReport.cshtml
Hint:
- Check whether you have added reference to the Razor Class Library that contains the view files.
- Check whether the view file name is correct or exists at the given path.
- Refer documentation or file issue here: https://github.com/soundaranbu/RazorTemplating
    at Razor.Templating.Core.RazorViewToStringRenderer.FindView(ActionContext actionContext, String viewName, Boolean isMainPage)
   at Razor.Templating.Core.RazorViewToStringRenderer.RenderViewToStringAsync(String viewName, Object model, ViewDataDictionary viewDataDictionary, Boolean isMainPage)
   at Razor.Templating.Core.RazorTemplateEngineRenderer.RenderAsync(String viewName, Object viewModel, Dictionary`2 viewBagOrViewData)
   at Razor.Templating.Core.RazorTemplateEngine.RenderAsync(String viewName, Object viewModel, Dictionary`2 viewBagOrViewData)
   at SoftConvergence.TalentManager.Analytics.AnalyticsReportBuilder.BuildReportAsync(String reportKey, AnalyticsData data) in /Users/oliviermatrot/Documents/SoftConvergence/Janus/SoftConvergence.TalentManager.Analytics/AnalyticsReportBuilder.cs:line 12
   at SoftConvergence.TalentManager.Analytics.PSRHMonthtlyAnalyticsReport.RenderReportContentAsync() in /Users/oliviermatrot/Documents/SoftConvergence/Janus/SoftConvergence.TalentManager.Analytics/PSRHMonthtlyAnalyticsReport.cs:line 22
   at SoftConvergence.TalentManager.Analytics.Test.AnalyticsReportTest.TestPSRHMonthlyReport() in /Users/oliviermatrot/Documents/SoftConvergence/Janus/SoftConvergence.TalentManager.Analytics.Test/AnalyticsReportTest.cs:line 12
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
```

Thanks in advance.

**Comment by soundaranbu** [comment] 2024-03-17 13:47
Hi @omatrot, thanks for raising the issue. I don't think we can directly accept the stream because of the way the underlying MVC razor view engine works. To load the views from different sources, the MVC has a concept of file providers. Using this approach, there's an example to load the views from absolute path in the README [here](https://github.com/soundaranbu/Razor.Templating.Core?tab=readme-ov-file#how-to-render-razor-views-from-absolute-path)

For your use case, I would imagine that you will need to add a [EmbeddedFileProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.fileproviders.embeddedfileprovider?view=dotnet-plat-ext-8.0) like this https://learn.microsoft.com/en-us/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-8.0#load-aspnet-core-features. 

Please give it a try & let me know. 

I'll also try in the mean time, if I get a chance. Thanks

**Comment by omatrot** [comment] 2024-03-17 14:16
Another option, maybe simpler, would for the API to accept a string with the content of the `.cshtml` file.

**Comment by soundaranbu** [comment] 2024-04-09 19:12
Hey @omatrot, I attempted this before as part of #26. But dropped this idea in favor of the `IFileProvider` which will cover almost any scenario and 1-1 match with ASP.NET Core. I'm keeping the other issue open to add some real world examples. 

For anyone looking for an example in the interim, please refer to this repo for custom file provider implementation: https://github.com/Joffreyvl/RazorTemplating.Function/blob/master/FunctionApp1/Program.cs

I'm closing this issue as it's a duplicate of #26

**Closed by soundaranbu** 2024-04-09 19:12 UTC

**Comment by vanillajonathan** [comment] 2024-07-05 13:09
Perhaps the RazorTemplating library could take in a `Stream` as a parameter then internally create a custom file provider and add the `Stream` to it?

```csharp
public class StreamFileProvider : IFileProvider
{
    private readonly Stream _stream;

    public StreamFileProvider(Stream stream)
    {
        _stream = stream;
    }

    public IFileInfo GetFileInfo(string subpath)
    {
        return new SteamFileInfo(_stream);
    }
}

public class SteamFileInfo : IFileInfo
{
    private readonly Stream _stream;

    internal SteamFileInfo(Stream stream)
    {
        _stream = stream;
    }

    public bool Exists => true;
    public bool IsDirectory => false;
    public DateTimeOffset LastModified => DateTimeOffset.Now;
    public long Length => _stream.Length;

    public Stream CreateReadStream() => _stream;
}
```
